config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)
  root to: 'movies#index'
  resources :questions

  post "/solutions/:id" => "solutions#create"

  resources :texts

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'csv'
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  after_initialize :set_default_value

  validates :title, presence: true
  validates :content, presence: true

  has_many :solutions

  private

    def set_default_value

      self.views ||= 0

    end

end

app/models/solution.rb
class Solution < ApplicationRecord

    validates :content, presence: true

    belongs_to :question
end

app/models/text.rb
class Text < ApplicationRecord

  validates :number, presence: true
  validates :genre, presence: true
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
          :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!
  #Railsの動画教材ページ（＝トップページ）へ
  def index
    @movies = Movie.page(params[:page])
  end



end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all.order(created_at: :desc)
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.save
    flash[:success] = "質問を追加しました。"
    redirect_to action: :index
  end

  def show

    @question = Question.find_by(id: params[:id])
    @solution = Solution.new

    @question.views += 1
    @question.save

  end

  private
    def question_params
      params.require(:question).permit(:title, :content)
    end

end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController

  def create
    @solution = Solution.new(content: solution_params[:content], question_id: params[:id])
    @solution.save
    if @solution.save
      flash[:success] = "回答を追加しました。"
      redirect_to('/questions')
    else
      @question = Question.find_by(id: params[:id])
      render('questions/show')
    end
  end

  private

  def solution_params
    params.require(:solution).permit(:content)
  end

end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

  def index
    @texts = Text.all.order(number: :asc)
  end

  def show
    @text = Text.find_by(id: params[:id])
  end

  def new
    @text = Text.new
  end

  def create
    @text = Text.new(text_params)
    @text.save
    flash[:success] = "テキスト教材を追加しました。"
    redirect_to action: :index
  end

  private

  def text_params
    params.require(:text).permit(:number, :genre, :title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"
    require "coderay"

    class HTMLwithCoderay < Redcarpet::Render::HTML
        def block_code(code, language)
            language = language.split(':')[0] if language.present?

            case language.to_s
            when 'rb'
                lang = :ruby
            when 'yml'
                lang = :yaml
            when 'css'
                lang = :css
            when 'html'
                lang = :html
            when ''
                lang = :md
            else
                lang = language
            end

            CodeRay.scan(code, lang).div
        end
    end

    def markdown(text)
        html_render = HTMLwithCoderay.new(
          filter_html: true,
          hard_wrap: true,
          link_attributes: { rel: 'nofollow', target: "_blank" }
        )
        options = {
            autolink: true,
            space_after_headers: true,
            no_intra_emphasis: true,
            fenced_code_blocks: true,
            tables: true,
            hard_wrap: true,
            xhtml: true,
            lax_html_blocks: true,
            strikethrough: true
        }
        extensions = {
            fenced_code_blocks: true
        }
        markdown = Redcarpet::Markdown.new(html_render, options)
        markdown.render(text)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GyakutenCloneGroup7</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- レスポンシブに対応 -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= render 'shared/header' %>

    <%= render 'shared/flash' unless devise_controller?%>

    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div id="container">
  <section id="movie">
    <div class="container">
      <div class="rows">
        <div class="text-center">
          <div class="col-xs-12">
          <% @movies.each do |movie| %>
            <div class="movie-title">
              <%= movie.title%>
            </div>
            <div class="movie-contents">
              <iframe width="560" height="315" src="<%= movie.url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
          <% end %>
          <div class="pagenate-container">
            <%= paginate @movies %>
          </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/questions/index.html.erb
<div id="container">
  <div class=".container">
    <h1> 新規投稿</h1>
    <%= form_with model: @question, url: questions_path, method: "POST", local: true do |form| %>
    <div class="form-group">
      <%= form.label :title, "【質問】", class: "form-label" %>
      <%= form.text_area :title, required: true, class: "form-control initial-height", rows: 3 %>
    </div>
    <div class="form-group">
      <%= form.label :content, "【詳細】", class: "form-label" %>
      <%= form.text_area :content, required: true, class: "form-control initial-height", rows: 5 %>
    </div>
    <div class="form-group">
      <%= form.submit('送信',class: 'btn btn-primary btn-block btn-lg') %>
    </div>
    <% end %>
  </div>

  <section id="questions">
    <div class="container">
      <% @questions.each do |question| %>
        <div class="questions-container">
          <a href="/questions/<%= question[:id] %>">
            <div class="question">
              <div class="row">
                <div class="col-md-7">
                  <div class="title-container">
                    <p class="title"><%= question.title %></p>
                  </div>
                </div>
                <div class="col-md-5">
                  <div class="info text-right">
                    <p>質問日　<%= l question.created_at, format: :default %></p>
                    <!--<p><%= question.views %>&nbsp;<%= question.views>=2 ? "views" : "view" %></p>-->
                    <p><%= pluralize(question.views, "view", locale: :en) %></p>
                  </div>
                </div>
              </div>
            </div>
          </a>
        </div>
      <% end %>
    </div>
  </section>

</div>

app/views/questions/show.html.erb
<div id="container">

  <section id="question">
    <div class="title">
      <h3>【質問】</h3>
      <p>
        <%= markdown(@question.title).html_safe %>
        </p>
    </div>
    <hr>
    <div class="detail">
      <h3>【詳細】</h3>
      <p>
        <%= markdown(@question.content).html_safe %>
        </p>
    </div>
    <hr>

    <% if @question.solutions.length >= 2 %>
        <% @question.solutions.each.with_index(1) do |solution, idx| %>
          <div class="solution">
            <h3>【回答<%= idx %>】</h3>
            <p>
              <%= markdown(solution.content).html_safe %>
              </p>
          </div>
        <% end %>
      <% elsif @question.solutions[0] %>
        <div class="solution">
          <h3>【回答】</h3>
          <p>
            <%= markdown(@question.solutions[0].content).html_safe %>
            </p>
        </div>
    <% end %>
  </section>

  <%= form_for @solution, url: "/solutions/#{@question.id}", method: :post do |f| %>
    <div class="container">
      <h1>回答投稿</h1>
      <p>【回答】</p>
      <p><%= f.text_area :content, class: "form-control initial-height", rows: 5 %></p>
      <div class="form-group">
        <%= f.submit('送信',class: 'btn btn-primary btn-block btn-lg') %>
      </div>
    </div>
  <% end %>

</div>

app/views/shared/_error_messages.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value) %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-danger">

  <a class="navbar-brand" href="/">Gyakuten</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Rails
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/">動画教材</a>
          <a class="dropdown-item" href="/texts">テキスト教材</a>
          <a class="dropdown-item" href="#">ライブコーディング</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/questions">質問集</a>
        </div>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">AWS講座 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">PHP講座 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">対談 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">情報発信 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">動画編集講座 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">ライティング講座 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">LINE@ <span class="sr-only">(current)</span></a>
      </li>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-default mud-white hover-white' %>
      </li>
    <% else %>
      <li class="nav-item active">
        <%= link_to "ログイン", new_user_session_path, class: 'post btn btn-default text-white' %>
      </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/texts/index.html.erb
<div id="container">

    <h2 class="text-center"><%= link_to "新規投稿（非オリジナル仕様）", new_text_path %></h2>

    <h2 class="text-center">Railsテキスト教材</h2>

    <table class="table table-striped">
      <thead class="bg-danger text-white">
        <tr>
          <th class="text-nowrap">No.</th>
          <th class="text-nowrap">ジャンル</th>
          <th class="text-nowrap">内容</th>
        </tr>
      </thead>
      <tbody id="myTable">
        <% @texts.each do |text| %>
          <tr>
            <td><%= text.number %></td>
            <td><%= text.genre %></td>
            <td><%= link_to text.title, text_path(text) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>

app/views/texts/new.html.erb
<%= form_for @text do |f| %>
    <div class="container">
      <h3>番号（No.）</h3>
      <p><%= f.number_field :number, class: "form-control initial-height" %></p>
      <h3>ジャンル</h3>
      <p><%= f.select :genre, [["Basic","Basic"], ["Ruby","Ruby"], ["Ruby on Rails","Ruby on Rails"]], :prompt => "選択してください", class: "form-control initial-height" %></p>
      <h3>タイトル</h3>
      <p><%= f.text_field :title, class: "form-control initial-height" %></p>
      <h3>内容</h3>
      <p><%= f.text_area :content, class: "form-control initial-height", rows: 5 %></p>
      <div class="form-group">
        <%= f.submit('送信',class: 'btn btn-primary btn-block btn-lg') %>
      </div>
    </div>
<% end %>

app/views/texts/show.html.erb
<div id="container">

    <%= markdown(@text.content).html_safe %>

</div>